SET TIME ZONE 'Asia/Dhaka';

ALTER TABLE "RetailPurchaseDraft"
  ALTER COLUMN "date" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "date" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "User"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Seller"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Driver"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "DriverTrip"
  ALTER COLUMN "date" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "date" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "settledAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "settledAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Customer"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Product"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Party"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Warehouse"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "PurchaseOrder"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "PurchaseOrderItem"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Lot"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "StockMove"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "SalesOrder"
  ALTER COLUMN "confirmedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "confirmedAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "SalesOrderItem"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Account"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Investor"
  ALTER COLUMN "startDate" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "startDate" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "InvestorTxn"
  ALTER COLUMN "date" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "date" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "Voucher"
  ALTER COLUMN "vdate" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "vdate" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "postedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "postedAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "deletedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "deletedAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "VoucherRow"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "RecurringExpenseTemplate"
  ALTER COLUMN "lastPostedDate" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "lastPostedDate" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "RecurringExpensePost"
  ALTER COLUMN "postedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "postedAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "AuditLog"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "VoucherReversal"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka';

ALTER TABLE "BusinessInfo"
  ALTER COLUMN "createdAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "createdAt" AT TIME ZONE 'Asia/Dhaka',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3) WITHOUT TIME ZONE USING "updatedAt" AT TIME ZONE 'Asia/Dhaka';
